// Market score engine v2/v3, ported line-for-line from
// property_analysis_dashboard.py (calculate_market_score_v2 / _v3 and
// helpers). Pure functions: data in, score out — no I/O.
//
// PARITY NOTE: this port is deliberately bug-for-bug so the numbers match
// the old app exactly (verified by tests/scoring.parity.test.ts against
// fixtures generated by running the Python engine):
//   * inverse ladder checks warning_above BEFORE danger_above, so the
//     danger score (15) is unreachable for household_debt/stress/unemployment
//   * direct ladder checks deficit_below BEFORE crisis_below — same shadowing
//   * v3 seeds from v2's base_score ROUNDED to 1dp (that's what v2 stores)
//   * composite override guards use Python truthiness (a 0 value is skipped)
// Fixing these changes the headline score and should be its own reviewed
// commit with updated fixtures.

import { INDICATORS_CONFIG, CYCLE_START_YEAR, CYCLE_LENGTH, STALE_AFTER_DAYS } from './config';
import { round1, roundHalfEven, fmtF } from './pyformat';

export interface DataPoint {
  date: string; // ISO yyyy-mm-dd
  value: number;
  source?: string | null;
}

/** All points for one indicator, any order — the engine sorts internally. */
export type SeriesMap = Record<string, DataPoint[]>;

export interface PropertyPoint {
  date: string;
  location: string;
  metric_name: string;
  value: number;
}

export interface IndicatorScore {
  value: number;
  score: number;
  trend: string;
  trend_change: number;
  trend_bonus: number;
  weight: number;
  description: string;
}

export interface ScoreV2Result {
  score: number;
  signal: string;
  breakdown: Record<string, unknown> & {
    base_score?: number;
    cycle_multiplier?: number;
    final_score?: number;
    cycle_position?: number;
    cycle_warning?: string;
    risk_warnings?: string[];
    indicator_scores?: Record<string, IndicatorScore>;
    data_completeness?: number;
    total_weight?: number;
    error?: string;
  };
}

function sortedByDateDesc(points: DataPoint[]): DataPoint[] {
  return [...points].sort((a, b) => (a.date < b.date ? 1 : a.date > b.date ? -1 : 0));
}

function latestPoint(points: DataPoint[] | undefined): DataPoint | null {
  if (!points || points.length === 0) return null;
  return sortedByDateDesc(points)[0];
}

/** Calendar-month subtraction matching SQLite date(x, '-N months') overflow
 *  semantics (May 31 - 3 months -> Mar 3). Postgres INTERVAL clamps to the
 *  month end instead; the difference only matters on the last 1-3 days of
 *  some months and only shifts which points fall inside a trend window. */
function monthsAgoISO(now: Date, months: number): string {
  const d = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth() - months, now.getUTCDate()));
  return d.toISOString().slice(0, 10);
}

/** Port of get_indicator_trend: two most recent points within N months. */
export function getIndicatorTrend(
  points: DataPoint[] | undefined,
  now: Date,
  months = 3,
): [string, number] {
  const cutoff = monthsAgoISO(now, months);
  const recent = sortedByDateDesc(points ?? []).filter((p) => p.date >= cutoff).slice(0, 2);
  if (recent.length < 2) return ['stable', 0];
  const latest = recent[0].value;
  const previous = recent[1].value;
  if (previous === 0) return ['stable', 0];
  const changePct = ((latest - previous) / previous) * 100;
  if (Math.abs(changePct) < 5) return ['stable', changePct];
  return changePct > 0 ? ['rising', changePct] : ['falling', changePct];
}

/** Port of calculate_volatility_penalty: population std over last N months. */
export function calculateVolatilityPenalty(
  points: DataPoint[] | undefined,
  now: Date,
  months = 6,
): [number, number, string] {
  const cutoff = monthsAgoISO(now, months);
  const values = (points ?? []).filter((p) => p.date >= cutoff).map((p) => p.value);
  if (values.length < 3) return [0, 0, 'insufficient_data'];
  const mean = values.reduce((a, b) => a + b, 0) / values.length;
  const variance = values.reduce((a, b) => a + (b - mean) * (b - mean), 0) / values.length;
  const stdDev = Math.sqrt(variance);
  const cv = mean !== 0 ? (stdDev / mean) * 100 : 0;
  if (cv > 20) return [-10, stdDev, 'extreme'];
  if (cv > 10) return [-5, stdDev, 'high'];
  if (cv > 5) return [-2, stdDev, 'moderate'];
  return [0, stdDev, 'low'];
}

function signalForScore(finalScore: number): string {
  if (finalScore >= 75) return '🟢 Strong Buy';
  if (finalScore >= 60) return '🟢 Buy';
  if (finalScore >= 50) return '🟡 Moderate Buy';
  if (finalScore >= 40) return '🟡 Hold';
  if (finalScore >= 30) return '🟠 Caution';
  return '🔴 Wait';
}

/** Python truthiness for composite guards: null/undefined/0 all skip. */
function truthy(v: number | null | undefined): v is number {
  return v !== null && v !== undefined && v !== 0;
}

export function cyclePosition(now: Date): number {
  const years = now.getUTCFullYear() - CYCLE_START_YEAR;
  const pos = years % CYCLE_LENGTH;
  return pos < 0 ? pos + CYCLE_LENGTH : pos;
}

export function calculateMarketScoreV2(series: SeriesMap, now: Date): ScoreV2Result {
  const indicatorScores: Record<string, IndicatorScore> = {};
  let totalWeight = 0;
  let weightedScoreSum = 0;
  let dataQuality = 0;
  const totalPossibleQuality = Object.keys(INDICATORS_CONFIG).length;

  for (const [indicatorName, config] of Object.entries(INDICATORS_CONFIG)) {
    const latest = latestPoint(series[indicatorName]);
    if (!latest) continue;
    const value = latest.value;
    dataQuality += 1;

    let indicatorScore = 50;

    if (config.impact === 'inverse') {
      if (config.optimal_below !== undefined && value < config.optimal_below) {
        indicatorScore = 85;
      } else if (config.healthy_below !== undefined && value < config.healthy_below) {
        indicatorScore = 75;
      } else if (config.warning_above !== undefined && value > config.warning_above) {
        indicatorScore = 35;
      } else if (config.danger_above !== undefined && value > config.danger_above) {
        indicatorScore = 15;
      } else if (config.optimal_min !== undefined && config.optimal_max !== undefined) {
        if (config.optimal_min <= value && value <= config.optimal_max) {
          indicatorScore = 80;
        } else if (value < config.optimal_min) {
          indicatorScore = 65;
        } else if (value > (config.danger_above as number)) {
          indicatorScore = 15;
        } else {
          indicatorScore = 40;
        }
      }
    } else if (config.impact === 'direct') {
      if (config.optimal_above !== undefined && value >= config.optimal_above) {
        indicatorScore = 85;
      } else if (config.strong_above !== undefined && value >= config.strong_above) {
        indicatorScore = 75;
      } else if (config.healthy_above !== undefined && value >= config.healthy_above) {
        indicatorScore = 65;
      } else if (config.deficit_below !== undefined && value < config.deficit_below) {
        indicatorScore = 35;
      } else if (config.crisis_below !== undefined && value < config.crisis_below) {
        indicatorScore = 15;
      } else if (config.weak_below !== undefined && value < config.weak_below) {
        indicatorScore = 40;
      }
    }

    let trendBonus = 0;
    if (config.trend_matters) {
      const [trendDirection, trendChange] = getIndicatorTrend(series[indicatorName], now, 3);
      if (config.impact === 'inverse') {
        if (trendDirection === 'falling') trendBonus = 10;
        else if (trendDirection === 'rising') trendBonus = -10;
      } else {
        if (trendDirection === 'rising') trendBonus = 10;
        else if (trendDirection === 'falling') trendBonus = -10;
      }
      indicatorScores[indicatorName] = {
        value,
        score: indicatorScore,
        trend: trendDirection,
        trend_change: trendChange,
        trend_bonus: trendBonus,
        weight: config.weight,
        description: config.description,
      };
    } else {
      indicatorScores[indicatorName] = {
        value,
        score: indicatorScore,
        trend: 'n/a',
        trend_change: 0,
        trend_bonus: 0,
        weight: config.weight,
        description: config.description,
      };
    }

    const finalIndicatorScore = Math.max(0, Math.min(100, indicatorScore + trendBonus));
    weightedScoreSum += finalIndicatorScore * config.weight;
    totalWeight += config.weight;
  }

  if (totalWeight === 0) {
    return { score: 50, signal: 'Insufficient Data', breakdown: { error: 'No data available' } };
  }

  let baseScore = weightedScoreSum / totalWeight;

  const riskWarnings: string[] = [];
  const getValue = (name: string) => indicatorScores[name]?.value ?? null;

  const debtGdp = getValue('household_debt_gdp');
  const interestRate = getValue('interest_rate');
  const stressRate = getValue('mortgage_stress_rate');
  const vacancy = getValue('rental_vacancy_rate');
  const approvals = getValue('building_approvals');
  const clearance = getValue('auction_clearance_rate');
  const unemployment = getValue('unemployment_rate');

  if (truthy(debtGdp) && debtGdp > 120 && truthy(interestRate) && interestRate > 5.5 && truthy(stressRate) && stressRate > 35) {
    baseScore = Math.min(baseScore, 25);
    riskWarnings.push('⚠️ PERFECT STORM: High debt + High rates + High stress');
  }
  if (truthy(stressRate) && stressRate > 40 && truthy(unemployment) && unemployment > 6.0) {
    baseScore = Math.min(baseScore, 30);
    riskWarnings.push('🚨 CRISIS: Extreme mortgage stress + Rising unemployment');
  }
  if (truthy(vacancy) && vacancy < 1.5 && truthy(approvals) && approvals < 180000 && truthy(clearance) && clearance > 70) {
    baseScore = Math.min(100, baseScore + 15);
    riskWarnings.push('✨ OPPORTUNITY: Severe supply shortage + Strong demand');
  }
  if (truthy(vacancy) && vacancy > 3.5 && truthy(approvals) && approvals > 250000) {
    baseScore = Math.max(20, baseScore - 15);
    riskWarnings.push('⚠️ OVERSUPPLY: High vacancy + Excessive building');
  }

  const position = cyclePosition(now);
  let cycleMultiplier = 1.0;
  let cycleWarning: string;
  const posLabel = fmtF(position, 0);
  if (position >= 14 && position <= 18) {
    cycleMultiplier = 0.9;
    cycleWarning = `⚠️ Late Cycle (Year ${posLabel}/18.6) - Exercise Caution`;
  } else if (position >= 0 && position <= 4) {
    cycleMultiplier = 1.1;
    cycleWarning = `✨ Early Cycle (Year ${posLabel}/18.6) - Prime Opportunity Window`;
  } else if (position >= 7 && position <= 11) {
    cycleMultiplier = 1.05;
    cycleWarning = `📈 Mid Cycle (Year ${posLabel}/18.6) - Strong Growth Phase`;
  } else {
    cycleWarning = `📊 Cycle Year ${posLabel}/18.6`;
  }

  let finalScore = baseScore * cycleMultiplier;
  finalScore = Math.max(0, Math.min(100, finalScore));

  let signal = signalForScore(finalScore);

  const dataCompleteness = (dataQuality / totalPossibleQuality) * 100;
  if (dataCompleteness < 50) signal += ' (Low Confidence)';

  return {
    score: finalScore,
    signal,
    breakdown: {
      base_score: round1(baseScore),
      cycle_multiplier: cycleMultiplier,
      final_score: round1(finalScore),
      cycle_position: round1(position),
      cycle_warning: cycleWarning,
      risk_warnings: riskWarnings,
      indicator_scores: indicatorScores,
      data_completeness: round1(dataCompleteness),
      total_weight: totalWeight,
    },
  };
}

export interface SubScores {
  affordability: number;
  supply_demand: number;
  financial_stress: number;
  momentum: number;
  trend_breakdown: Record<string, number>;
}

export function calculateSubScores(indicatorScores: Record<string, IndicatorScore>): SubScores {
  const get = (name: string) => indicatorScores[name];

  const affordability: number[] = [];
  const interest = get('interest_rate');
  if (interest) affordability.push((interest.score ?? 50) * 0.4);
  const debt = get('household_debt_gdp');
  if (debt) affordability.push((debt.score ?? 50) * 0.3);
  const stress = get('mortgage_stress_rate');
  if (stress) affordability.push((stress.score ?? 50) * 0.3);
  const affordabilityScore = affordability.length ? affordability.reduce((a, b) => a + b, 0) : 50;

  const supplyDemand: number[] = [];
  const vacancy = get('rental_vacancy_rate');
  if (vacancy) supplyDemand.push((vacancy.score ?? 50) * 0.35);
  const approvals = get('building_approvals');
  if (approvals) supplyDemand.push((approvals.score ?? 50) * 0.35);
  const clearance = get('auction_clearance_rate');
  if (clearance) supplyDemand.push((100 - (clearance.score ?? 50)) * 0.3);
  const supplyDemandScore = supplyDemand.length ? supplyDemand.reduce((a, b) => a + b, 0) : 50;

  const financialStress: number[] = [];
  const unemployment = get('unemployment_rate');
  if (unemployment) financialStress.push((unemployment.score ?? 50) * 0.4);
  if (stress) financialStress.push((stress.score ?? 50) * 0.4);
  const credit = get('credit_growth');
  if (credit) financialStress.push((credit.score ?? 50) * 0.2);
  const financialStressScore = financialStress.length ? financialStress.reduce((a, b) => a + b, 0) : 50;

  const momentum: number[] = [];
  const trendCount: Record<string, number> = { rising: 0, falling: 0, stable: 0 };
  const configImpact: Record<string, Impact> = {
    interest_rate: 'inverse',
    household_debt_gdp: 'inverse',
    rental_vacancy_rate: 'inverse',
    mortgage_stress_rate: 'inverse',
    unemployment_rate: 'inverse',
    building_approvals: 'direct',
    auction_clearance_rate: 'direct',
    credit_growth: 'direct',
    wage_growth: 'direct',
  };
  for (const [indName, indData] of Object.entries(indicatorScores)) {
    const trend = indData.trend ?? 'stable';
    if (trend !== 'n/a') {
      trendCount[trend] = (trendCount[trend] ?? 0) + 1;
      const impact = configImpact[indName] ?? 'direct';
      if (impact === 'direct' && trend === 'rising') momentum.push(70);
      else if (impact === 'direct' && trend === 'falling') momentum.push(30);
      else if (impact === 'inverse' && trend === 'falling') momentum.push(70);
      else if (impact === 'inverse' && trend === 'rising') momentum.push(30);
      else momentum.push(50);
    }
  }
  const momentumScore = momentum.length ? momentum.reduce((a, b) => a + b, 0) / momentum.length : 50;

  return {
    affordability: round1(affordabilityScore),
    supply_demand: round1(supplyDemandScore),
    financial_stress: round1(financialStressScore),
    momentum: round1(momentumScore),
    trend_breakdown: trendCount,
  };
}

type Impact = 'inverse' | 'direct';

export interface RegionalAnalysis {
  locations: Record<string, { score: number; data: Record<string, number> }>;
  divergence: number;
  ranked: Array<[string, { score: number; data: Record<string, number> }]>;
  recommendation: 'selective' | 'broad';
}

export function calculateRegionalDivergence(
  propertyData: PropertyPoint[],
  now: Date,
): RegionalAnalysis | null {
  const cutoff = monthsAgoISO(now, 6);
  const locations = [...new Set(propertyData.filter((p) => p.date >= cutoff).map((p) => p.location))].sort();
  if (locations.length < 2) return null;

  const metricsToCheck = ['median_price', 'rental_yield', 'vacancy_rate', 'days_on_market', 'annual_growth'];
  const locationScores: RegionalAnalysis['locations'] = {};

  for (const location of locations) {
    const locationData: Record<string, number> = {};
    for (const metric of metricsToCheck) {
      const rows = propertyData
        .filter((p) => p.location === location && p.metric_name === metric)
        .sort((a, b) => (a.date < b.date ? 1 : -1));
      if (rows.length) locationData[metric] = rows[0].value;
    }
    let score = 50;
    if ('rental_yield' in locationData && locationData.rental_yield > 4.5) score += 15;
    if ('vacancy_rate' in locationData && locationData.vacancy_rate < 2.0) score += 15;
    if ('annual_growth' in locationData && locationData.annual_growth > 5) score += 20;
    locationScores[location] = { score: Math.min(100, score), data: locationData };
  }

  const scoresList = Object.values(locationScores).map((v) => v.score);
  const divergence = scoresList.length ? Math.max(...scoresList) - Math.min(...scoresList) : 0;
  const ranked = Object.entries(locationScores).sort((a, b) => b[1].score - a[1].score);

  return {
    locations: locationScores,
    divergence,
    ranked,
    recommendation: divergence > 30 ? 'selective' : 'broad',
  };
}

export function calculateConfidenceInterval(
  baseScore: number,
  dataCompleteness: number,
  volatilityLevels: Record<string, string>,
): [number, number, string] {
  const dataUncertainty = (100 - dataCompleteness) / 10;
  let volatilityUncertainty = 0;
  for (const level of Object.values(volatilityLevels)) {
    if (level === 'extreme') volatilityUncertainty += 3;
    else if (level === 'high') volatilityUncertainty += 2;
    else if (level === 'moderate') volatilityUncertainty += 1;
  }
  let totalUncertainty = dataUncertainty + volatilityUncertainty;
  totalUncertainty = Math.min(totalUncertainty, 20);
  const lower = Math.max(0, baseScore - totalUncertainty);
  const upper = Math.min(100, baseScore + totalUncertainty);
  const confidence = totalUncertainty < 5 ? 'High' : totalUncertainty < 10 ? 'Medium' : 'Low';
  return [round1(lower), round1(upper), confidence];
}

export interface ScoreV3Result {
  score: number;
  signal: string;
  breakdown: Record<string, unknown> & {
    volatility_analysis?: Record<string, { penalty: number; std_dev: number; level: string }>;
    total_volatility_penalty?: number;
    score_after_volatility?: number;
    score_after_cycle?: number;
    sub_scores?: SubScores;
    regional_analysis?: RegionalAnalysis | null;
    confidence_interval?: { lower: number; upper: number; level: string; range: number };
    final_score_v3?: number;
  };
}

const V3_KEY_INDICATORS = [
  'interest_rate',
  'household_debt_gdp',
  'mortgage_stress_rate',
  'rental_vacancy_rate',
  'unemployment_rate',
];

export function calculateMarketScoreV3(
  series: SeriesMap,
  propertyData: PropertyPoint[],
  now: Date,
): ScoreV3Result {
  const v2 = calculateMarketScoreV2(series, now);
  // v2 stores base_score rounded to 1dp; v3 deliberately seeds from that
  // rounded value (parity with the Python original)
  const trueBaseScore = (v2.breakdown.base_score as number | undefined) ?? v2.score;
  const indicatorScores = (v2.breakdown.indicator_scores ?? {}) as Record<string, IndicatorScore>;

  const volatilityAnalysis: Record<string, { penalty: number; std_dev: number; level: string }> = {};
  const volatilityPenalties: number[] = [];
  for (const indicator of V3_KEY_INDICATORS) {
    if (indicator in indicatorScores) {
      const [penalty, stdDev, level] = calculateVolatilityPenalty(series[indicator], now, 6);
      volatilityAnalysis[indicator] = { penalty, std_dev: roundHalfEven2(stdDev), level };
      volatilityPenalties.push(penalty);
    }
  }

  const totalVolatilityPenalty = volatilityPenalties.reduce((a, b) => a + b, 0);
  const scoreAfterVolatility = trueBaseScore + totalVolatilityPenalty;

  const subScores = calculateSubScores(indicatorScores);
  const regionalAnalysis = calculateRegionalDivergence(propertyData, now);

  const cycleMultiplier = (v2.breakdown.cycle_multiplier as number | undefined) ?? 1.0;
  const scoreAfterCycle = scoreAfterVolatility * cycleMultiplier;

  const dataCompleteness = (v2.breakdown.data_completeness as number | undefined) ?? 50;
  const volLevels: Record<string, string> = Object.fromEntries(
    Object.entries(volatilityAnalysis).map(([k, v]) => [k, v.level]),
  );
  const [lowerBound, upperBound, confidenceLevel] = calculateConfidenceInterval(
    scoreAfterCycle,
    dataCompleteness,
    volLevels,
  );

  let finalScore = Math.max(0, Math.min(100, scoreAfterCycle));

  let signal = signalForScore(finalScore);
  if (confidenceLevel === 'Low') signal += ' (Low Confidence)';
  else if (confidenceLevel === 'Medium') signal += ' (Medium Confidence)';

  return {
    score: finalScore,
    signal,
    breakdown: {
      ...v2.breakdown,
      volatility_analysis: volatilityAnalysis,
      total_volatility_penalty: totalVolatilityPenalty,
      score_after_volatility: round1(scoreAfterVolatility),
      score_after_cycle: round1(scoreAfterCycle),
      sub_scores: subScores,
      regional_analysis: regionalAnalysis,
      confidence_interval: {
        lower: lowerBound,
        upper: upperBound,
        level: confidenceLevel,
        range: round1(upperBound - lowerBound),
      },
      final_score_v3: round1(finalScore),
    },
  };
}

function roundHalfEven2(x: number): number {
  return roundHalfEven(x, 2);
}

// ---------------------------------------------------------------------------
// Audit — new capability (not in the Python app): per-indicator freshness so
// stale single-point indicators are visible instead of silently anchoring
// the score.

export interface IndicatorAudit {
  indicator: string;
  display_name: string;
  latest_date: string | null;
  latest_value: number | null;
  days_old: number | null;
  stale: boolean;
  point_count: number;
  sources: Record<string, number>;
}

export function buildAudit(series: SeriesMap, now: Date): IndicatorAudit[] {
  const names = new Set([...Object.keys(INDICATORS_CONFIG), ...Object.keys(series)]);
  const result: IndicatorAudit[] = [];
  for (const name of names) {
    const points = series[name] ?? [];
    const latest = latestPoint(points);
    const daysOld = latest
      ? Math.floor((now.getTime() - new Date(latest.date + 'T00:00:00Z').getTime()) / 86400000)
      : null;
    const sources: Record<string, number> = {};
    for (const p of points) {
      const s = p.source ?? 'unknown';
      sources[s] = (sources[s] ?? 0) + 1;
    }
    result.push({
      indicator: name,
      display_name: INDICATORS_CONFIG[name]?.display_name ?? name.replace(/_/g, ' '),
      latest_date: latest?.date ?? null,
      latest_value: latest?.value ?? null,
      days_old: daysOld,
      stale: daysOld === null || daysOld > STALE_AFTER_DAYS,
      point_count: points.length,
      sources,
    });
  }
  return result.sort((a, b) => (INDICATORS_CONFIG[b.indicator]?.weight ?? 0) - (INDICATORS_CONFIG[a.indicator]?.weight ?? 0));
}
