// Golden-master parity: the TypeScript engine must reproduce the outputs of
// the original Python engine (property_analysis_dashboard.py) exactly.
//
// tests/fixtures/golden.json was generated by running the REAL Python
// functions against synthetic SQLite databases (see the fixture generator in
// the repo history / scratchpad). Regenerate with a fresh `generated_on`
// date if the scenarios change — the engine is clock-sensitive (trend and
// volatility windows), so tests evaluate at the fixture's generation date.

import { describe, it, expect } from 'vitest';
import { calculateMarketScoreV2, calculateMarketScoreV3 } from '../src/lib/scoring/engine';
import type { SeriesMap, PropertyPoint, IndicatorScore } from '../src/lib/scoring/engine';
import { generateAutoCommentary } from '../src/lib/scoring/commentary';
import golden from './fixtures/golden.json';

interface FixtureIndicator {
  name: string;
  date: string;
  value: number;
}

function toSeries(indicators: FixtureIndicator[]): SeriesMap {
  const map: SeriesMap = {};
  for (const row of indicators) {
    (map[row.name] ??= []).push({ date: row.date, value: row.value });
  }
  return map;
}

// The Python engine ran with datetime.now() on the generation day.
const NOW = new Date(`${golden.generated_on}T12:00:00Z`);
// The old app's commentary used the 2011 anchor; production now uses 2008.
const LEGACY_COMMENTARY_ANCHOR = 2011;

const scenarios = Object.entries(golden.scenarios);

describe.each(scenarios)('scenario: %s', (_name, fixture) => {
  const series = toSeries(fixture.inputs.indicators);
  const propertyData: PropertyPoint[] = fixture.inputs.property_data.map(
    (p: { location: string; metric: string; date: string; value: number }) => ({
      date: p.date,
      location: p.location,
      metric_name: p.metric,
      value: p.value,
    }),
  );

  it('matches v2 score, signal, and breakdown', () => {
    const v2 = calculateMarketScoreV2(series, NOW);
    expect(v2.score).toBeCloseTo(fixture.v2.score, 9);
    expect(v2.signal).toBe(fixture.v2.signal);

    const fb = fixture.v2.breakdown as Record<string, unknown>;
    if ('error' in fb) {
      expect(v2.breakdown.error).toBe(fb.error);
      return;
    }
    expect(v2.breakdown.base_score).toBeCloseTo(fb.base_score as number, 9);
    expect(v2.breakdown.cycle_multiplier).toBeCloseTo(fb.cycle_multiplier as number, 9);
    expect(v2.breakdown.final_score).toBeCloseTo(fb.final_score as number, 9);
    expect(v2.breakdown.cycle_position).toBeCloseTo(fb.cycle_position as number, 9);
    expect(v2.breakdown.cycle_warning).toBe(fb.cycle_warning);
    expect(v2.breakdown.risk_warnings).toEqual(fb.risk_warnings);
    expect(v2.breakdown.data_completeness).toBeCloseTo(fb.data_completeness as number, 9);
    expect(v2.breakdown.total_weight).toBe(fb.total_weight);

    const expectedScores = fb.indicator_scores as Record<string, IndicatorScore>;
    expect(Object.keys(v2.breakdown.indicator_scores ?? {}).sort()).toEqual(
      Object.keys(expectedScores).sort(),
    );
    for (const [name, expected] of Object.entries(expectedScores)) {
      const actual = (v2.breakdown.indicator_scores ?? {})[name];
      expect(actual.value, `${name}.value`).toBeCloseTo(expected.value, 9);
      expect(actual.score, `${name}.score`).toBe(expected.score);
      expect(actual.trend, `${name}.trend`).toBe(expected.trend);
      expect(actual.trend_change, `${name}.trend_change`).toBeCloseTo(expected.trend_change, 6);
      expect(actual.trend_bonus, `${name}.trend_bonus`).toBe(expected.trend_bonus);
      expect(actual.weight, `${name}.weight`).toBe(expected.weight);
      expect(actual.description, `${name}.description`).toBe(expected.description);
    }
  });

  it('matches v3 score, signal, and breakdown', () => {
    const v3 = calculateMarketScoreV3(series, propertyData, NOW);
    expect(v3.score).toBeCloseTo(fixture.v3.score, 9);
    expect(v3.signal).toBe(fixture.v3.signal);

    const fb = fixture.v3.breakdown as Record<string, unknown>;
    expect(v3.breakdown.total_volatility_penalty).toBe(fb.total_volatility_penalty);
    expect(v3.breakdown.score_after_volatility).toBeCloseTo(fb.score_after_volatility as number, 9);
    expect(v3.breakdown.score_after_cycle).toBeCloseTo(fb.score_after_cycle as number, 9);
    expect(v3.breakdown.final_score_v3).toBeCloseTo(fb.final_score_v3 as number, 9);

    const expectedVol = fb.volatility_analysis as Record<
      string,
      { penalty: number; std_dev: number; level: string }
    >;
    expect(Object.keys(v3.breakdown.volatility_analysis ?? {}).sort()).toEqual(
      Object.keys(expectedVol).sort(),
    );
    for (const [name, expected] of Object.entries(expectedVol)) {
      const actual = (v3.breakdown.volatility_analysis ?? {})[name];
      expect(actual.penalty, `${name}.penalty`).toBe(expected.penalty);
      expect(actual.std_dev, `${name}.std_dev`).toBeCloseTo(expected.std_dev, 6);
      expect(actual.level, `${name}.level`).toBe(expected.level);
    }

    const expectedSub = fb.sub_scores as Record<string, unknown>;
    expect(v3.breakdown.sub_scores?.affordability).toBeCloseTo(expectedSub.affordability as number, 9);
    expect(v3.breakdown.sub_scores?.supply_demand).toBeCloseTo(expectedSub.supply_demand as number, 9);
    expect(v3.breakdown.sub_scores?.financial_stress).toBeCloseTo(
      expectedSub.financial_stress as number,
      9,
    );
    expect(v3.breakdown.sub_scores?.momentum).toBeCloseTo(expectedSub.momentum as number, 9);
    expect(v3.breakdown.sub_scores?.trend_breakdown).toEqual(expectedSub.trend_breakdown);

    const expectedCi = fb.confidence_interval as Record<string, unknown>;
    expect(v3.breakdown.confidence_interval?.lower).toBeCloseTo(expectedCi.lower as number, 9);
    expect(v3.breakdown.confidence_interval?.upper).toBeCloseTo(expectedCi.upper as number, 9);
    expect(v3.breakdown.confidence_interval?.level).toBe(expectedCi.level);
    expect(v3.breakdown.confidence_interval?.range).toBeCloseTo(expectedCi.range as number, 9);

    const expectedRegional = fb.regional_analysis as null | {
      divergence: number;
      recommendation: string;
      locations: Record<string, { score: number; data: Record<string, number> }>;
      ranked: Array<[string, { score: number }]>;
    };
    if (expectedRegional === null) {
      expect(v3.breakdown.regional_analysis).toBeNull();
    } else {
      const actual = v3.breakdown.regional_analysis!;
      expect(actual.divergence).toBe(expectedRegional.divergence);
      expect(actual.recommendation).toBe(expectedRegional.recommendation);
      expect(Object.keys(actual.locations).sort()).toEqual(
        Object.keys(expectedRegional.locations).sort(),
      );
      for (const [loc, exp] of Object.entries(expectedRegional.locations)) {
        expect(actual.locations[loc].score, `${loc}.score`).toBe(exp.score);
        expect(actual.locations[loc].data, `${loc}.data`).toEqual(exp.data);
      }
      expect(actual.ranked.map((r) => r[0])).toEqual(expectedRegional.ranked.map((r) => r[0]));
    }
  });

  it('matches the auto-generated commentary text exactly', () => {
    const v3 = calculateMarketScoreV3(series, propertyData, NOW);
    const commentary = generateAutoCommentary(
      series,
      v3.score,
      v3.signal,
      NOW,
      LEGACY_COMMENTARY_ANCHOR,
    );
    expect(commentary).toBe(fixture.commentary);
  });
});
